{
 "title": "Immich",
 "description": "Immich Dashboard\n\nhttps://github.com/eithan1231/immich-exporter",
 "tags": [ "immich" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "promsource", "label": "Prometheus Source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Disk Size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "immich_storage_disk_size", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Disk Use",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "immich_storage_disk_use", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Disk Available",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "immich_storage_disk_available", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Disk Usage Percentage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "immich_storage_disk_usage_percentage",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Photo Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "immich_statistics_photo_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Video Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "immich_statistics_video_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "immich_statistics_usage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "User Photos",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "immich_statistics_user_photo_count",
     "legendFormat": "{{user_name}}"
    }
   ]
  },
  {
   "title": "User Videos",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 5, "x": 5, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "immich_statistics_user_video_count",
     "legendFormat": "{{user_name}}"
    }
   ]
  },
  {
   "title": "User Usage",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 5, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "immich_statistics_user_usage", "legendFormat": "{{user_name}}" }
   ]
  }
 ]
}